version: '3.9'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb_service_mymoney
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mymoney
    volumes:
      - ./backend/db:/data/db